@echo off
echo 🚀 Запуск Python FastAPI сервера с активацией venv...
call venv\Scripts\activate.bat
echo 📦 Установка зависимостей...
pip install PyJWT requests beautifulsoup4 lxml langchain-google-community fastapi uvicorn python-multipart yandexcloud
echo 🚀 Запуск сервера...
python start-python-server.py
