"""add tracking_id to request_supplier

Revision ID: 363d205a76d5
Revises: f59a337a4a45
Create Date: 2026-05-24 04:44:49.151843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363d205a76d5'
down_revision: Union[str, Sequence[str], None] = 'f59a337a4a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_suppliers', sa.Column('tracking_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'request_suppliers', ['tracking_id'])
    op.drop_constraint(op.f('requests_tracking_id_key'), 'requests', type_='unique')
    op.drop_column('requests', 'tracking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('requests_tracking_id_key'), 'requests', ['tracking_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'request_suppliers', type_='unique')
    op.drop_column('request_suppliers', 'tracking_id')
    # ### end Alembic commands ###
