"""remove currency and delivery_deadline from requests

Revision ID: 42f8e9c7d1a2
Revises: c141813191ad
Create Date: 2026-05-23 21:02:24.354545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42f8e9c7d1a2"
down_revision: str | Sequence[str] | None = "c141813191ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "delivery_deadline")
    op.drop_column("requests", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column("currency", sa.String(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "requests",
        sa.Column(
            "delivery_deadline",
            sa.DateTime(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
