"""Remove unique on supplier email

Revision ID: 51da5c487171
Revises: 430be685aa1d
Create Date: 2026-05-15 01:24:04.083242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51da5c487171'
down_revision: Union[str, Sequence[str], None] = '430be685aa1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('suppliers_email_key'), 'suppliers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('suppliers_email_key'), 'suppliers', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
