"""change tid from uuid to 8char

Revision ID: 6451c206371b
Revises: 67f8c249728e
Create Date: 2026-05-24 14:42:32.571671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6451c206371b'
down_revision: Union[str, Sequence[str], None] = '67f8c249728e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_suppliers', 'tracking_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_suppliers', 'tracking_id',
               existing_type=sa.String(length=16),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
