"""remove unnecessary columns from request; add is_enabled column to supplier

Revision ID: 73b9bfb2e1f2
Revises: 96fad4387156
Create Date: 2026-05-22 01:43:35.178096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73b9bfb2e1f2'
down_revision: Union[str, Sequence[str], None] = '96fad4387156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_suppliers', sa.Column('is_enabled', sa.Boolean(), nullable=False))
    op.add_column('requests', sa.Column('additional_params', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('requests', 'delivery_region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('requests', 'unit')
    op.drop_column('requests', 'quality_requirements')
    op.drop_column('requests', 'max_price_per_unit')
    op.drop_column('requests', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('max_price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('quality_requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('requests', 'delivery_region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('requests', 'additional_params')
    op.drop_column('request_suppliers', 'is_enabled')
    # ### end Alembic commands ###
