"""add user specific columns to suppliers for creation

Revision ID: 78ed7252bcfa
Revises: 73b9bfb2e1f2
Create Date: 2026-05-22 21:17:51.387648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ed7252bcfa'
down_revision: Union[str, Sequence[str], None] = '73b9bfb2e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('added_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'users', ['added_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'added_by_user_id')
    # ### end Alembic commands ###
