"""Make smtp_message_id nullable

Revision ID: 83b931d51263
Revises: b33e140df70d
Create Date: 2026-05-13 21:31:38.144363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b931d51263'
down_revision: Union[str, Sequence[str], None] = 'b33e140df70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_suppliers', 'smtp_message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_suppliers', 'smtp_message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
