"""add contact_email, business_info coulumns to user, add cascade

Revision ID: 965b6c281fea
Revises: 363d205a76d5
Create Date: 2026-05-24 13:03:55.852970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965b6c281fea'
down_revision: Union[str, Sequence[str], None] = '363d205a76d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('request_suppliers_request_id_fkey'), 'request_suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'request_suppliers', 'requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('response_analyses_response_id_fkey'), 'response_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'response_analyses', 'supplier_responses', ['response_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('supplier_responses_request_supplier_id_fkey'), 'supplier_responses', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_responses', 'request_suppliers', ['request_supplier_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_info')
    op.drop_column('users', 'contact_email')
    op.drop_constraint(None, 'supplier_responses', type_='foreignkey')
    op.create_foreign_key(op.f('supplier_responses_request_supplier_id_fkey'), 'supplier_responses', 'request_suppliers', ['request_supplier_id'], ['id'])
    op.drop_constraint(None, 'response_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('response_analyses_response_id_fkey'), 'response_analyses', 'supplier_responses', ['response_id'], ['id'])
    op.drop_constraint(None, 'request_suppliers', type_='foreignkey')
    op.create_foreign_key(op.f('request_suppliers_request_id_fkey'), 'request_suppliers', 'requests', ['request_id'], ['id'])
    # ### end Alembic commands ###
