"""Add agree_terms, agree_marketing columns

Revision ID: 96fad4387156
Revises: 51da5c487171
Create Date: 2026-05-20 17:21:57.790304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fad4387156'
down_revision: Union[str, Sequence[str], None] = '51da5c487171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agree_terms', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('agree_marketing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agree_marketing')
    op.drop_column('users', 'agree_terms')
    # ### end Alembic commands ###
