"""rename email -> main_email; add extra_emails columns

Revision ID: ab7db7801a58
Revises: cf208df5ccd1
Create Date: 2026-05-25 20:28:07.363720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab7db7801a58'
down_revision: Union[str, Sequence[str], None] = 'cf208df5ccd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_suppliers', sa.Column('sent_status', sa.String(), nullable=False))
    op.drop_column('request_suppliers', 'status')
    op.add_column('suppliers', sa.Column('main_email', sa.String(), nullable=False))
    op.add_column('suppliers', sa.Column('extra_emails', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.drop_column('suppliers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('suppliers', 'extra_emails')
    op.drop_column('suppliers', 'main_email')
    op.add_column('request_suppliers', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('request_suppliers', 'sent_status')
    # ### end Alembic commands ###
