"""Add body email text and from_source to suppliers

Revision ID: b33e140df70d
Revises: 5f59f025ea0a
Create Date: 2026-05-12 22:04:06.601147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33e140df70d'
down_revision: Union[str, Sequence[str], None] = '5f59f025ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_suppliers', sa.Column('body_text', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('from_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'from_source')
    op.drop_column('request_suppliers', 'body_text')
    # ### end Alembic commands ###
