"""Make subscription plan primary key

Revision ID: c141813191ad
Revises: 3e907043749a
Create Date: 2026-05-13 23:48:43.113583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c141813191ad'
down_revision: Union[str, Sequence[str], None] = '3e907043749a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'id')
    op.add_column('supplier_responses', sa.Column('imap_id', sa.String(), nullable=True))
    op.drop_column('supplier_responses', 'imap_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_responses', sa.Column('imap_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('supplier_responses', 'imap_id')
    op.add_column('subscriptions', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
