"""add email_subject to requests

Revision ID: e6225a678cd2
Revises: 6451c206371b
Create Date: 2026-05-24 20:32:37.517898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6225a678cd2'
down_revision: Union[str, Sequence[str], None] = '6451c206371b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('email_subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'email_subject')
    # ### end Alembic commands ###
