"""change fk to subscription

Revision ID: f67b0fb6e5ad
Revises: 4bfd46feed61
Create Date: 2026-05-28 23:16:40.233502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67b0fb6e5ad'
down_revision: Union[str, Sequence[str], None] = '4bfd46feed61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'subscriptions', ['plan'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'id')
    # ### end Alembic commands ###
